# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72e7c08855f83221f650f7d684d45017048f574348e9ec3d9d24c3c05c5938cc1aa071a69cf91e8b54be6282a759385d45a0aceb84a37e430f8377041f8edbfe

test:
  secret_key_base: ae5f8e6430d9f1140bc3cff3a87ac3e0b65dcd660c6af886bb6b790d82bd48ebfd8ad2c2739194e14656080302704a06a7e7a39a974e8dab4637cf92d507926a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
